### ISSUE TITLE
Visual Studio Test Explorer unable to discover Cucumber tests.

### ISSUE THREAD

**Issue by Daniel8770** [ttutisani/Xunit.Gherkin.Quick#143]
Hi

I previously made an issue about the Visual Studio test explorer not being able to discover my Cucumber tests. Back then the problem seemed to fix itself, but now I am back to the same problem.

The test explorer is able to find all other unit tests written in the NUnit framework, but not the Cucumber tests.

I use the following FeatureFileAttribute: `[FeatureFile(@".*\.feature", FeatureFilePathType.Regex)]`.

I have the Xunit.Gherkin.Quick repo cloned and currently not using the NUGet packet.

I am unable to find and run the scenarios of the Project Consumer tests in the XUnit.Gherkin.Quick solution as well.

Based on the error messages from below, it seems like I am missing some test adapters, however I have the `xunit `and `xunit.runner.visualstudio` packages  installed within my project and I have tried updating both of them.

When rebuilding the project the following is outputted in the Visual Studio tests output:

```
========== Starting test discovery ==========
No suitable test runtime provider was found for any source in this run.
Skipping source: C:\Projects\ProcessWork\CaseGuideTesting\Xunit.Gherkin.Quick\bin\Debug\netstandard1.5\Xunit.Gherkin.Quick.dll (.NETStandard,Version=v1.5, X64)

Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process for source(s) 'C:\Projects\ProcessWork\CaseGuideTesting\CBrain.F2.Rest.CucumberTesting\bin\Debug\net6.0\CBrain.F2.Rest.CucumberTesting.dll' exited with error: You must install or update .NET to run this application.
App: C:\Projects\ProcessWork\CaseGuideTesting\CBrain.F2.Rest.CucumberTesting\bin\Debug\net6.0\testhost.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.21' (x64)
.NET location: C:\Program Files\dotnet\
The following frameworks were found:
  5.0.17 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  7.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.21&arch=x64&rid=win10-x64
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(IEnumerable`1 sources, Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters)
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process for source(s) 'C:\Projects\ProcessWork\CaseGuideTesting\UnitTests\bin\Debug\net6.0\UnitTests.dll' exited with error: You must install or update .NET to run this application.
App: C:\Projects\ProcessWork\CaseGuideTesting\UnitTests\bin\Debug\net6.0\testhost.exe
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.21' (x64)
.NET location: C:\Program Files\dotnet\
The following frameworks were found:
  5.0.17 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  6.0.20 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  7.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.21&arch=x64&rid=win10-x64
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(IEnumerable`1 sources, Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters)
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process for source(s) 'C:\Projects\ProcessWork\CaseGuideTesting\CBrain.F2.Rest.CucumberTesting\bin\Debug\net6.0\CBrain.F2.Rest.CucumberTesting.dll' exited with error: . Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(IEnumerable`1 sources, Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters)
========== Test discovery aborted: 0 Tests found in 485,1 ms ==========
Test project Xunit.Gherkin.Quick does not reference any .NET NuGet adapter. Test discovery or execution might not work for this project.
It's recommended to reference NuGet test adapters in each test project in the solution.
```

**Comment by Daniel8770** [comment]
I solved the problem now, by installing .NET SDK 6.0.
